{
    head:{
        title:"注册账户"
    },
    body:{
        Caption:"创建账户",
        CustomerName:"你的名字",
        NameError:"请输入你的名字",
        ApEmail:"邮箱",
        EmailMissing:"请输入你的邮箱",
        ApPassword:"密码",
        PasswordPlaceholder:"至少包含6个字符",
        PasswordTip:"密码必须至少包含6个字符。",
        ReEnterPassword:"重新输入密码",
        ReEnterError:"密码必须相同",
        Next:"下一步",
        Already:"已经有一个帐户？",
        Footer:{
            FooterLink1:"我要开店",
            FooterLink2:"亚马逊物流",
            FooterLink3:"Amazon Payments",
            FooterLink4:"亚马逊广告",
            FooterLink5:"在欧洲销售",
            FooterLink6:"在日本销售",
            FooterLink7:"帮助",
        },
        Inc:"版权所有 © 1996-2018，亚马逊公司或其关联公司"
    }
}