{
    head: {
        title: "Account Info"
    },
    body: {
        shopper:"Seller Account Information",
        Welcome:"Welcome",
        SellerInformation:"Your Seller Profile",
        CommodityState:"Listings Status",
        HolidaySetting:"Going on a vacation?",
        CurrentState:"Current Status of Listings:",
        NotAvailableSale :"Inactive (Listings not  available for sale on Amazon)",
        Service:"Your Services",
        Administration:"Manage",
        Shop:"Sell On Amazon",
        Major:"Professional",
        Personal:"Individual",
        Logistics:"Fulfillment by Amazon",
        Register:"Registered",
        PaymentInformation:"Payment Information",
        DepositMethod:"Deposit Methods",
        PaymentMethod:"Charge Methods",
        BusinessInformation:"Business Information",
        OfficeAddress:"Business Address",
        CorporateName:"Legal Entity",
        RegisteredAddress:"Official Registered Address",
        SellerMark:"Your Merchant Token",
        UploadingData:"Language for feed processing report",
        DisplayName:"Display Name",
        Deliver:"Shipping and Returns Information",
        ReturnInformation:"Return Address",
        DistributionSetting:"Shipping Settings",
        InternationalReturn:"International Returns Providers",
        PreferenceSetting:"Buy Shipping preferences",
        TaxInformation:"Tax Information",
        CommonProblem:"FAQ",
        ClosingAccount:"I signed up for an account by mistake or don’t need it anymore. How do I close the account?",
        StopSelling:"I am taking time off (vacation). How can I temporarily deactivate my listings?",
        SaleGoods:"Why are my items no longer for sale?",
        IneffectiveInformation:"Why did my credit card have an error or have 'Invalid Information'?",
        RelatedLinks:"Related Links",
        FirstOption:"Notification Preferences",
        LoginSettings:"Login Settings",
        Closing:"Close account" 
    }
}