{
    head:{
        title:"Billing / Deposit"
    },
    Settings:"Settings",
    Logout:"Logout",
    body:{
        Agreement:"Seller agreement",
        Information:"Seller Information",
        Deposit:"Billing / Deposit",
        Tax:"Tax information",
        Product:"Product information",
        Caption1:"Set up your billing method",
        SellingPlan:"Your selling plan:",
        Professional:"Professional selling plan",
        ViewDetails:"view plan details",
        ViewPlanDetails:{
            Fee:"Total monthly subscription fee : $39.99 + additional selling fees. You will only be charged once you complete setting up your account.",
            checkboxT1:"Fulfillment by Amazon",
            checkboxC1:"Gain access to Amazon's world-class fulfillment resources and expertise, acclaimed customer services and PRIME and FREE shipping options.",
            Pay:"Pay per use",
            checkboxT2:"Sell on Amazon Business",
            checkboxC2:"Enable business seller features and gain access to Amazon business buyers. No additional fee. Amazon business sellers must adhere to the program performance requirements."
        },
        CreditCard:"Your credit card information",
        CardInformation:"Your first monthly subscription fee ($39.99) will be charged upon account creation. You’ll be able to list products after we perform payment validation, which typically takes an hour (but could take up to 24 hours).",
        CardNumber:"Card Number",
        CardNumberError:"Please enter the correct card number",
        ValidThrough:"Valid through",
        CardDateError:"The expiration date is not valid",
        CardholderName:"Cardholder's Name",
        CardholderNameError:"Please fill in cardholder's name",
        NewAddress:"Add a new address",
        Addaddress:{
            Street:"Street address",
            City:"City / Town",
            Province:"State / Region / Province",
            Country:"Country/Region",
            ZIP:"ZIP / Postal Code"
        },
        AddressField:{
            StreetError:"treet address is Invalid",
            CityError:"City / Town is Invalid",
            ProvinceError:"State / Region / Province is Invalid",
            ZIPError:"ZIP / Postal Code is Invalid"
        },
        Caption2:"Set up your deposit method",
        BankInformation:"Enter your bank information to receive payments from Amazon",
        WhyAsk:"Why do we ask for your bank information?",
        WhyAskContent:"We need a valid bank account to disburse your Amazon sales proceeds. Make sure you enter banking information accurately. Editing this information later can result in delayed payments while we review the account for your security.",
        BankLocation:"Bank Location",
        HolderName:"Account Holder's Name",
        HolderNameInput:"Name as on bank documents",
        HolderNameHover:"Account Holder Name must match the name on your bank account. Do not include the name of your bank. Example: John Doe or Company XYZ. Match what your bank has on file using ISO basic Latin characters. This information must be accurate in order to receive your payments.",
        RoutingNumber:"9-Digit Routing Number",
        RoutingNumberInput:"9 digits",
        RoutingNumberError:"Please enter the correct number",
        HolderError:"Required field！",
        RoutingNumberHover:"(Federal ABA Number) Provide a routing number for Automated Clearing House (ACH) or electronic funds transfers instead of wire transfers. Please contact your bank for assistance.",
        AccountNumber:"Bank Account Number",
        AccountNumberHover:"Your account must be enabled to receive deposits through the Automated Clearing House (ACH). Please contact your bank for assistance. (Up to 19 digits)",
        Retype:"Re-type Bank Account Number",
        RetypeError:"Please enter the same account!",
        Back:"Back",
        Next:"Next",
        Rate:"Rate this page",
        Support:"Get support",
        Policies:"Policies and Agreements",
        Inc:"© 1999-2018, Amazon.com, Inc. or its affiliates"
    }
}